//
//  BookDetailView.swift
//  Shlf
//
//  Created by João Fernandes on 26/11/2025.
//

import SwiftUI
import OSLog
import SwiftData

struct BookDetailView: View {
    @Environment(\.modelContext) private var modelContext
    @Environment(\.dismiss) private var dismiss
    @Environment(\.themeColor) private var themeColor
    @Bindable var book: Book
    @Query private var profiles: [UserProfile]
    @Query private var activeSessions: [ActiveReadingSession]

    @State private var showLogSession = false
    @State private var showEditBook = false
    @State private var showDeleteAlert = false
    @State private var showConfetti = false
    @State private var showAddQuote = false
    @State private var showResumeAlert = false
    @State private var pendingResumePosition: BookPosition?
    @State private var showStatusChangeAlert = false
    @State private var pendingStatus: ReadingStatus?
    @State private var savedProgress: Int?

    private var profile: UserProfile? {
        profiles.first
    }

    private var hasActiveSession: Bool {
        activeSessions.first != nil
    }

    var body: some View {
        ScrollView {
            VStack(spacing: Theme.Spacing.lg) {
                bookHeader

                // Modern Status Selector
                statusSelector

                if hasActiveSession {
                    activeSessionBanner
                }

                if book.readingStatus == .currentlyReading {
                    if profile?.useProgressSlider == true {
                        ProgressSliderView(
                            book: book,
                            incrementAmount: profile?.pageIncrementAmount ?? 1,
                            showButtons: profile?.showSliderButtons ?? false,
                            showConfetti: $showConfetti,
                            onSave: { pagesRead in
                                handleProgressSave(pagesRead: pagesRead)
                            }
                        )
                        .transition(.asymmetric(
                            insertion: .scale.combined(with: .opacity),
                            removal: .scale(scale: 0.95).combined(with: .opacity)
                        ))
                    } else {
                        QuickProgressStepper(
                            book: book,
                            incrementAmount: profile?.pageIncrementAmount ?? 1,
                            showConfetti: $showConfetti,
                            onSave: { pagesRead in
                                handleProgressSave(pagesRead: pagesRead)
                            }
                        )
                        .transition(.asymmetric(
                            insertion: .scale.combined(with: .opacity),
                            removal: .scale(scale: 0.95).combined(with: .opacity)
                        ))
                    }
                }

                if let description = book.bookDescription, profile?.showDescription ?? true {
                    descriptionSection(description)
                }

                if profile?.showMetadata ?? true {
                    metadataSection
                }

                if book.readingStatus == .currentlyReading {
                    progressSection
                }

                // Last Reading Position
                if let lastPos = book.lastPosition {
                    lastPositionSection(lastPos)
                }

                if let subjects = book.subjects, !subjects.isEmpty, profile?.showSubjects ?? true {
                    subjectsSection(subjects)
                }

                // Quotes Section
                if let quotes = book.quotes, !quotes.isEmpty {
                    quotesSection(quotes)
                }

                let hideAuto = profile?.hideAutoSessionsIPhone ?? false
                let hasVisibleSessions = (book.readingSessions ?? []).contains(where: { session in
                    hideAuto ? !session.isAutoGenerated : true
                })
                if hasVisibleSessions, profile?.showReadingHistory ?? true {
                    readingHistorySection
                }

                if !book.notes.isEmpty, profile?.showNotes ?? true {
                    notesSection
                }
            }
            .padding(Theme.Spacing.md)
        }
        .background(Theme.Colors.background)
        .confetti(isActive: $showConfetti)
        .navigationTitle(book.title)
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Menu {
                    if book.readingStatus == .currentlyReading {
                        Button {
                            showLogSession = true
                        } label: {
                            Label("Log Reading Session", systemImage: "plus.circle")
                        }

                        Button {
                            markAsFinished()
                        } label: {
                            Label("Mark Finished", systemImage: "checkmark.circle")
                        }

                        Button {
                            book.readingStatus = .didNotFinish
                        } label: {
                            Label("Mark as DNF", systemImage: "xmark.circle")
                        }

                        Divider()
                    }

                    Button {
                        showEditBook = true
                    } label: {
                        Label("Edit", systemImage: "pencil")
                    }

                    Button(role: .destructive) {
                        showDeleteAlert = true
                    } label: {
                        Label("Delete", systemImage: "trash")
                    }
                } label: {
                    Image(systemName: "ellipsis.circle")
                }
            }
        }
        .sheet(isPresented: $showLogSession) {
            LogReadingSessionView(book: book)
        }
        .sheet(isPresented: $showEditBook) {
            EditBookView(book: book)
        }
        .sheet(isPresented: $showAddQuote) {
            AddQuoteView(book: book)
        }
        .alert("Delete Book?", isPresented: $showDeleteAlert) {
            Button("Delete", role: .destructive) {
                deleteBook()
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This will permanently delete \(book.title) and all reading sessions.")
        }
        .alert("Resume to Earlier Page?", isPresented: $showResumeAlert) {
            Button("Resume Anyway", role: .destructive) {
                if let position = pendingResumePosition {
                    book.currentPage = position.pageNumber
                }
                pendingResumePosition = nil
            }
            Button("Cancel", role: .cancel) {
                pendingResumePosition = nil
            }
        } message: {
            if let position = pendingResumePosition {
                Text("You're currently on page \(book.currentPage). Resuming will go back to page \(position.pageNumber).")
            }
        }
        .alert("Change Reading Status?", isPresented: $showStatusChangeAlert) {
            Button("Change Status", role: .destructive) {
                if let status = pendingStatus {
                    updateReadingStatus(to: status)
                }
                pendingStatus = nil
            }
            Button("Cancel", role: .cancel) {
                pendingStatus = nil
            }
        } message: {
            if let status = pendingStatus {
                Text("You're on page \(book.currentPage). Changing to \"\(status.rawValue)\" will reset your progress, but it will be saved and restored if you switch back to \"Currently Reading\".")
            }
        }
    }

    private var activeSessionBanner: some View {
        Button {
            showLogSession = true
        } label: {
            HStack(spacing: 12) {
                // Pulsing green dot
                Circle()
                    .fill(Color.green)
                    .frame(width: 10, height: 10)
                    .overlay(
                        Circle()
                            .stroke(Color.green.opacity(0.3), lineWidth: 3)
                            .scaleEffect(1.5)
                    )
                    .modifier(PulseAnimation())

                if let activeSession = activeSessions.first {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Active Session")
                            .font(.headline)
                            .foregroundStyle(.primary)
                        Text("Started on \(activeSession.sourceDevice) • \(activeSession.pagesRead) pages")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                Spacer()

                Image(systemName: "chevron.right")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .padding()
            .background(Color.green.opacity(0.1))
            .cornerRadius(12)
        }
        .buttonStyle(.plain)
    }

    private var statusSelector: some View {
        Menu {
            ForEach(ReadingStatus.allCases, id: \.self) { status in
                Button {
                    handleStatusChange(to: status)
                } label: {
                    HStack {
                        Image(systemName: status.icon)
                        Text(status.rawValue)
                        if book.readingStatus == status {
                            Spacer()
                            Image(systemName: "checkmark")
                        }
                    }
                }
            }
        } label: {
            HStack {
                Image(systemName: book.readingStatus.icon)
                    .font(.body)
                    .frame(width: 24)
                    .foregroundStyle(themeColor.color)

                Text(book.readingStatus.rawValue)
                    .font(Theme.Typography.body)
                    .foregroundStyle(Theme.Colors.text)

                Spacer()

                Image(systemName: "chevron.down")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(Theme.Colors.tertiaryText)
            }
            .padding(Theme.Spacing.md)
            .background(
                RoundedRectangle(cornerRadius: 12)
                    .fill(themeColor.color.opacity(0.08))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(themeColor.color.opacity(0.3), lineWidth: 1)
            )
        }
        .padding(.horizontal, Theme.Spacing.md)
    }

    private var bookHeader: some View {
        VStack(spacing: Theme.Spacing.md) {
            BookCoverView(
                imageURL: book.coverImageURL,
                title: book.title,
                width: 140,
                height: 210
            )

            VStack(spacing: Theme.Spacing.xs) {
                Text(book.title)
                    .font(Theme.Typography.title2)
                    .foregroundStyle(Theme.Colors.text)
                    .multilineTextAlignment(.center)

                Text(book.author)
                    .font(Theme.Typography.headline)
                    .foregroundStyle(Theme.Colors.secondaryText)
                    .multilineTextAlignment(.center)

                Label(book.bookType.rawValue, systemImage: book.bookType.icon)
                    .font(Theme.Typography.caption)
                    .foregroundStyle(Theme.Colors.tertiaryText)
            }
        }
    }

    private var progressSection: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            Text("Progress")
                .font(Theme.Typography.title3)
                .foregroundStyle(Theme.Colors.text)

            if let totalPages = book.totalPages {
                VStack(spacing: Theme.Spacing.sm) {
                    HStack {
                        Text("\(book.currentPage)")
                            .font(Theme.Typography.title)

                        Text("/ \(totalPages) pages")
                            .font(Theme.Typography.body)
                            .foregroundStyle(Theme.Colors.secondaryText)

                        Spacer()

                        Text("\(Int(book.progressPercentage))%")
                            .font(Theme.Typography.title2)
                            .foregroundStyle(themeColor.color)
                    }

                    ProgressView(value: book.progressPercentage, total: 100)
                        .tint(themeColor.color)
                }
                .padding(Theme.Spacing.md)
                .cardStyle()
            } else {
                Text("Total pages not set")
                    .font(Theme.Typography.body)
                    .foregroundStyle(Theme.Colors.secondaryText)
                    .frame(maxWidth: .infinity)
                    .padding(Theme.Spacing.md)
                    .cardStyle()
            }
        }
    }

    private func lastPositionSection(_ lastPos: BookPosition) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            HStack {
                Text("Last Reading Position")
                    .font(Theme.Typography.title3)
                    .foregroundStyle(Theme.Colors.text)

                Spacer()

                Button {
                    if book.currentPage > lastPos.pageNumber {
                        pendingResumePosition = lastPos
                        showResumeAlert = true
                    } else {
                        book.currentPage = lastPos.pageNumber
                    }
                } label: {
                    Label("Resume", systemImage: "arrow.forward.circle.fill")
                        .font(.caption)
                }
                .buttonStyle(.bordered)
                .tint(themeColor.color)
            }

            VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
                Text(lastPos.positionDescription)
                    .font(Theme.Typography.headline)
                    .foregroundStyle(Theme.Colors.text)

                if let note = lastPos.note {
                    Text(note)
                        .font(Theme.Typography.body)
                        .foregroundStyle(Theme.Colors.secondaryText)
                }

                Text("Saved \(lastPos.timestamp.formatted(date: .abbreviated, time: .shortened))")
                    .font(Theme.Typography.caption)
                    .foregroundStyle(Theme.Colors.tertiaryText)
            }
            .padding(Theme.Spacing.md)
            .frame(maxWidth: .infinity, alignment: .leading)
            .cardStyle()
        }
    }

    private func quotesSection(_ quotes: [Quote]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            HStack {
                Text("Saved Quotes")
                    .font(Theme.Typography.title3)
                    .foregroundStyle(Theme.Colors.text)

                Spacer()

                Button {
                    showAddQuote = true
                } label: {
                    Image(systemName: "plus.circle.fill")
                }
                .buttonStyle(.borderless)
                .foregroundStyle(themeColor.color)
            }

            ForEach(quotes.sorted { $0.dateAdded > $1.dateAdded }) { quote in
                NavigationLink {
                    QuoteDetailView(quote: quote, book: book)
                } label: {
                    QuoteRow(quote: quote)
                }
                .buttonStyle(.plain)
            }
        }
    }

    private var readingHistorySection: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            Text("Reading History")
                .font(Theme.Typography.title3)
                .foregroundStyle(Theme.Colors.text)

            // Filter sessions based on iPhone preference
            let hideAuto = profile?.hideAutoSessionsIPhone ?? false
            let sessions = (book.readingSessions ?? [])
                .filter { session in
                    hideAuto ? !session.isAutoGenerated : true
                }
                .sorted { $0.startDate > $1.startDate }

            ForEach(sessions) { session in
                ReadingSessionRow(session: session)
            }
        }
    }

    private var notesSection: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            Text("Notes")
                .font(Theme.Typography.title3)
                .foregroundStyle(Theme.Colors.text)

            Text(book.notes)
                .font(Theme.Typography.body)
                .foregroundStyle(Theme.Colors.secondaryText)
                .padding(Theme.Spacing.md)
                .frame(maxWidth: .infinity, alignment: .leading)
                .cardStyle()
        }
    }

    @ViewBuilder
    private func descriptionSection(_ description: String) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            Text("About This Book")
                .font(Theme.Typography.title3)
                .foregroundStyle(Theme.Colors.text)

            Text(description)
                .font(Theme.Typography.body)
                .foregroundStyle(Theme.Colors.secondaryText)
                .lineLimit(5)
                .padding(Theme.Spacing.md)
                .frame(maxWidth: .infinity, alignment: .leading)
                .cardStyle()
        }
    }

    @ViewBuilder
    private var metadataSection: some View {
        let hasAnyVisibleMetadata = (book.publisher != nil && (profile?.showPublisher ?? true)) ||
                                   (book.publishedDate != nil && (profile?.showPublishedDate ?? true)) ||
                                   (book.language != nil && (profile?.showLanguage ?? true)) ||
                                   (book.isbn != nil && (profile?.showISBN ?? true)) ||
                                   (book.totalPages != nil && (profile?.showReadingTime ?? true))

        if hasAnyVisibleMetadata {
            VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
                Text("Details")
                    .font(Theme.Typography.title3)
                    .foregroundStyle(Theme.Colors.text)

                VStack(spacing: Theme.Spacing.xs) {
                    if let publisher = book.publisher, profile?.showPublisher ?? true {
                        MetadataRow(label: "Publisher", value: publisher, icon: "building.2")
                    }

                    if let publishedDate = book.publishedDate, profile?.showPublishedDate ?? true {
                        MetadataRow(label: "Published", value: publishedDate, icon: "calendar")
                    }

                    if let language = book.language, profile?.showLanguage ?? true {
                        MetadataRow(label: "Language", value: language, icon: "globe")
                    }

                    if let isbn = book.isbn, profile?.showISBN ?? true {
                        MetadataRow(label: "ISBN", value: isbn, icon: "barcode")
                    }

                    if let totalPages = book.totalPages, profile?.showReadingTime ?? true {
                        let readingTime = estimateReadingTime(pages: totalPages)
                        MetadataRow(label: "Reading Time", value: readingTime, icon: "clock")
                    }
                }
                .padding(Theme.Spacing.md)
                .cardStyle()
            }
        }
    }

    @ViewBuilder
    private func subjectsSection(_ subjects: [String]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            Text("Genres & Topics")
                .font(Theme.Typography.title3)
                .foregroundStyle(Theme.Colors.text)
                .padding(.horizontal, Theme.Spacing.md)

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: Theme.Spacing.xs) {
                    ForEach(subjects, id: \.self) { subject in
                        Text(subject)
                            .font(Theme.Typography.caption)
                            .foregroundStyle(themeColor.color)
                            .padding(.horizontal, Theme.Spacing.sm)
                            .padding(.vertical, Theme.Spacing.xxs)
                            .background(themeColor.color.opacity(0.1))
                            .clipShape(Capsule())
                    }
                }
                .padding(.horizontal, Theme.Spacing.md)
            }
        }
    }

    private func estimateReadingTime(pages: Int) -> String {
        let minutesPerPage = 2.0
        let totalMinutes = Double(pages) * minutesPerPage
        let hours = Int(totalMinutes / 60)

        if hours < 1 {
            return "\(Int(totalMinutes)) min"
        } else if hours < 24 {
            return "~\(hours) hours"
        } else {
            let days = hours / 24
            return "~\(days) days"
        }
    }

    private func handleStatusChange(to status: ReadingStatus) {
        // If changing from Currently Reading with progress, show warning
        if book.readingStatus == .currentlyReading &&
           book.currentPage > 0 &&
           status != .currentlyReading {
            pendingStatus = status
            showStatusChangeAlert = true
        } else {
            updateReadingStatus(to: status)
        }
    }

    private func updateReadingStatus(to status: ReadingStatus) {
        let previousStatus = book.readingStatus

        // Save progress when leaving Currently Reading
        if previousStatus == .currentlyReading && status != .currentlyReading && book.currentPage > 0 {
            savedProgress = book.currentPage
        }

        book.readingStatus = status

        switch status {
        case .currentlyReading:
            if book.dateStarted == nil {
                book.dateStarted = Date()
            }
            // Offer to restore saved progress
            if let saved = savedProgress, saved > book.currentPage {
                book.currentPage = saved
            }
        case .finished:
            let previousPage = book.currentPage
            book.dateFinished = Date()
            if let totalPages = book.totalPages {
                book.currentPage = totalPages

                // Create session for the remaining pages if finishing from menu
                let pagesRead = totalPages - previousPage
                if pagesRead > 0 {
                    handleProgressSave(pagesRead: pagesRead)
                }
            }
            // Update goals when finishing a book
            if let profile = profile {
                let tracker = GoalTracker(modelContext: modelContext)
                tracker.updateGoals(for: profile)
            }
        case .wantToRead:
            // Reset progress if moving back to want to read
            if previousStatus != .wantToRead {
                book.currentPage = 0
                book.dateStarted = nil
                book.dateFinished = nil
            }
        case .didNotFinish:
            if book.dateFinished == nil {
                book.dateFinished = Date()
            }
        }

        // Sync to Watch whenever status changes
        Task {
            await WatchConnectivityManager.shared.syncBooksToWatch()
        }
    }

    private func markAsFinished() {
        updateReadingStatus(to: .finished)
    }

    private func handleProgressSave(pagesRead: Int) {
        // Create session with actual delta (can be negative for corrections)
        guard pagesRead != 0, let profile = profile else { return }

        let endPage = book.currentPage
        let startPage = endPage - pagesRead // Don't use max(), allow negative

        // Estimate reading time: industry standard is ~2 minutes per page
        let estimatedMinutes = abs(pagesRead) * 2

        let session = ReadingSession(
            startPage: startPage,
            endPage: endPage,
            durationMinutes: estimatedMinutes,
            xpEarned: 0, // Will be calculated below
            isAutoGenerated: true,
            book: book
        )

        // Calculate XP using the same engine as manual sessions
        let engine = GamificationEngine(modelContext: modelContext)
        session.xpEarned = engine.calculateXP(for: session)

        modelContext.insert(session)

        // Award XP/streak and achievements using authoritative engine
        engine.awardXP(session.xpEarned, to: profile)
        engine.updateStreak(for: profile, sessionDate: Date())
        engine.checkAchievements(for: profile)

        do {
            try modelContext.save()

            // Do ALL sync operations in background to avoid blocking UI
            let currentPage = book.currentPage
            Task.detached(priority: .userInitiated) {
                // Refresh Live Activity if it's running
                await ReadingSessionActivityManager.shared.updateActivity(
                    currentPage: currentPage,
                    xpEarned: session.xpEarned
                )

                // Keep Watch in sync with new session and stats
                await WatchConnectivityManager.shared.sendSessionToWatch(session)
                await WatchConnectivityManager.shared.sendProfileStatsToWatch(profile)

                // Export widget data
                await MainActor.run {
                    WidgetDataExporter.exportSnapshot(modelContext: modelContext)
                }
            }
        } catch {
            WatchConnectivityManager.logger.error("Failed to save quick session: \(error.localizedDescription)")
        }
    }

    private func deleteBook() {
        // Deleting a book cascade-deletes its sessions, so we need to recalculate stats
        modelContext.delete(book)

        // Recalculate stats after cascade deletion of sessions
        if let profile = profile {
            let engine = GamificationEngine(modelContext: modelContext)
            engine.recalculateStats(for: profile)
        }

        // Sync to Watch after deletion
        Task {
            await WatchConnectivityManager.shared.syncBooksToWatch()
            if let profile = profile {
                await WatchConnectivityManager.shared.sendProfileStatsToWatch(profile)
            }
        }

        // Update widget snapshot so deleted books disappear
        WidgetDataExporter.exportSnapshot(modelContext: modelContext)

        dismiss()
    }
}

struct ReadingSessionRow: View {
    let session: ReadingSession

    var body: some View {
        HStack(spacing: Theme.Spacing.md) {
            VStack(alignment: .leading, spacing: Theme.Spacing.xxs) {
                Text(session.startDate, style: .date)
                    .font(Theme.Typography.headline)
                    .foregroundStyle(Theme.Colors.text)

                Text(session.startDate, style: .time)
                    .font(Theme.Typography.caption)
                    .foregroundStyle(Theme.Colors.tertiaryText)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: Theme.Spacing.xxs) {
                HStack(spacing: Theme.Spacing.xs) {
                    Image(systemName: "book.pages")
                        .font(.caption)

                    Text("\(session.pagesRead) pages")
                        .font(Theme.Typography.callout)
                }
                .foregroundStyle(Theme.Colors.text)

                HStack(spacing: Theme.Spacing.xs) {
                    Image(systemName: "clock")
                        .font(.caption)

                    Text("\(session.durationMinutes) min")
                        .font(Theme.Typography.caption)
                }
                .foregroundStyle(Theme.Colors.secondaryText)

                if session.xpEarned > 0 {
                    HStack(spacing: Theme.Spacing.xxs) {
                        Image(systemName: "star.fill")
                            .font(.caption2)

                        Text("+\(session.xpEarned) XP")
                            .font(Theme.Typography.caption2)
                    }
                    .foregroundStyle(Theme.Colors.xpGradient)
                }
            }
        }
        .padding(Theme.Spacing.md)
        .cardStyle()
    }
}

struct MetadataRow: View {
    let label: String
    let value: String
    let icon: String

    var body: some View {
        HStack(spacing: Theme.Spacing.sm) {
            Image(systemName: icon)
                .font(.caption)
                .foregroundStyle(Theme.Colors.tertiaryText)
                .frame(width: 20)

            Text(label)
                .font(Theme.Typography.callout)
                .foregroundStyle(Theme.Colors.secondaryText)

            Spacer()

            Text(value)
                .font(Theme.Typography.callout)
                .foregroundStyle(Theme.Colors.text)
        }
    }
}

#Preview {
    NavigationStack {
        BookDetailView(book: Book(
            title: "The Great Gatsby",
            author: "F. Scott Fitzgerald",
            totalPages: 180,
            currentPage: 45,
            readingStatus: .currentlyReading,
            bookDescription: "A classic novel set in the Jazz Age, exploring themes of wealth, love, and the American Dream.",
            subjects: ["Fiction", "Classic Literature", "Romance", "American Literature"],
            publisher: "Scribner",
            publishedDate: "1925",
            language: "EN"
        ))
    }
    .modelContainer(for: [Book.self, ReadingSession.self], inMemory: true)
}

// Pulsing animation for active session indicator
struct PulseAnimation: ViewModifier {
    @State private var isAnimating = false

    func body(content: Content) -> some View {
        content
            .opacity(isAnimating ? 0.6 : 1.0)
            .scaleEffect(isAnimating ? 0.8 : 1.0)
            .animation(
                Animation.easeInOut(duration: 1.0)
                    .repeatForever(autoreverses: true),
                value: isAnimating
            )
            .onAppear {
                isAnimating = true
            }
    }
}
