//
//  ReadingDataExporter.swift
//  Shlf
//
//  Export reading data as JSON
//

import Foundation
import SwiftData

enum ReadingDataExporter {
    struct ExportPayload: Codable {
        let exportedAt: Date
        let appVersion: String
        let buildNumber: String
        let profile: ExportProfile?
        let books: [ExportBook]
        let sessions: [ExportSession]
        let goals: [ExportGoal]
        let quotes: [ExportQuote]
        let positions: [ExportPosition]
        let achievements: [ExportAchievement]
        let streakEvents: [ExportStreakEvent]
        let activeSessions: [ExportActiveSession]
    }

    struct ExportProfile: Codable {
        let id: String
        let totalXP: Int
        let currentStreak: Int
        let longestStreak: Int
        let lastReadingDate: Date?
        let streaksPaused: Bool
        let lastPardonDate: Date?
        let hasCompletedOnboarding: Bool
        let isProUser: Bool
        let cloudSyncEnabled: Bool
        let themeColorRawValue: String
        let showDescription: Bool
        let showMetadata: Bool
        let showSubjects: Bool
        let showReadingHistory: Bool
        let showNotes: Bool
        let showPublisher: Bool
        let showPublishedDate: Bool
        let showLanguage: Bool
        let showISBN: Bool
        let showReadingTime: Bool
        let pageIncrementAmount: Int
        let useProgressSlider: Bool
        let showSliderButtons: Bool
        let useCircularProgressWatch: Bool
        let enableWatchPositionMarking: Bool
        let hideAutoSessionsIPhone: Bool
        let hideAutoSessionsWatch: Bool
        let showSettingsOnWatch: Bool
        let autoEndSessionEnabled: Bool
        let autoEndSessionHours: Int
        let streakReminderEnabled: Bool
        let streakReminderHour: Int
        let streakReminderMinute: Int
        let streakReminderRespectFocus: Bool
        let chartTypeRawValue: String
        let heatmapPeriodRawValue: String
        let homeCardOrder: [String]
        let bookDetailSectionOrder: [String]
    }

    struct ExportBook: Codable {
        let id: String
        let title: String
        let author: String
        let isbn: String?
        let coverImageURL: String?
        let totalPages: Int?
        let currentPage: Int
        let savedCurrentPage: Int?
        let bookTypeRawValue: String
        let readingStatusRawValue: String
        let dateAdded: Date
        let dateStarted: Date?
        let dateFinished: Date?
        let notes: String
        let rating: Int?
        let goodreadsShelves: [String]?
        let bookDescription: String?
        let subjects: [String]?
        let publisher: String?
        let publishedDate: String?
        let language: String?
        let openLibraryWorkID: String?
        let openLibraryEditionID: String?
    }

    struct ExportSession: Codable {
        let id: String
        let bookId: String?
        let startDate: Date
        let endDate: Date?
        let startPage: Int
        let endPage: Int
        let durationMinutes: Int
        let xpEarned: Int
        let isAutoGenerated: Bool
        let countsTowardStats: Bool
        let isImported: Bool
        let xpAwarded: Bool
    }

    struct ExportGoal: Codable {
        let id: String
        let typeRawValue: String
        let targetValue: Int
        let currentValue: Int
        let startDate: Date
        let endDate: Date
        let isCompleted: Bool
        let createdAt: Date
    }

    struct ExportQuote: Codable {
        let id: String
        let bookId: String?
        let text: String
        let pageNumber: Int?
        let dateAdded: Date
        let note: String?
        let isFavorite: Bool
    }

    struct ExportPosition: Codable {
        let id: String
        let bookId: String?
        let pageNumber: Int
        let lineNumber: Int?
        let timestamp: Date
        let note: String?
    }

    struct ExportAchievement: Codable {
        let id: String
        let typeRawValue: String
        let unlockedAt: Date
        let isNew: Bool
    }

    struct ExportStreakEvent: Codable {
        let id: String
        let date: Date
        let typeRawValue: String
        let streakLength: Int
    }

    struct ExportActiveSession: Codable {
        let id: String
        let bookId: String?
        let startDate: Date
        let currentPage: Int
        let startPage: Int
        let isPaused: Bool
        let pausedAt: Date?
        let totalPausedDuration: TimeInterval
        let lastUpdated: Date
        let sourceDevice: String
    }

    @MainActor
    static func export(modelContext: ModelContext) throws -> URL {
        let books = try modelContext.fetch(FetchDescriptor<Book>())
        let sessions = try modelContext.fetch(FetchDescriptor<ReadingSession>())
        let goals = try modelContext.fetch(FetchDescriptor<ReadingGoal>())
        let quotes = try modelContext.fetch(FetchDescriptor<Quote>())
        let positions = try modelContext.fetch(FetchDescriptor<BookPosition>())
        let achievements = try modelContext.fetch(FetchDescriptor<Achievement>())
        let streakEvents = try modelContext.fetch(FetchDescriptor<StreakEvent>())
        let activeSessions = try modelContext.fetch(FetchDescriptor<ActiveReadingSession>())
        let profile = try modelContext.fetch(FetchDescriptor<UserProfile>()).first

        let exportProfile = profile.map { profile in
            ExportProfile(
                id: profile.id.uuidString,
                totalXP: profile.totalXP,
                currentStreak: profile.currentStreak,
                longestStreak: profile.longestStreak,
                lastReadingDate: profile.lastReadingDate,
                streaksPaused: profile.streaksPaused,
                lastPardonDate: profile.lastPardonDate,
                hasCompletedOnboarding: profile.hasCompletedOnboarding,
                isProUser: profile.isProUser,
                cloudSyncEnabled: profile.cloudSyncEnabled,
                themeColorRawValue: profile.themeColorRawValue,
                showDescription: profile.showDescription,
                showMetadata: profile.showMetadata,
                showSubjects: profile.showSubjects,
                showReadingHistory: profile.showReadingHistory,
                showNotes: profile.showNotes,
                showPublisher: profile.showPublisher,
                showPublishedDate: profile.showPublishedDate,
                showLanguage: profile.showLanguage,
                showISBN: profile.showISBN,
                showReadingTime: profile.showReadingTime,
                pageIncrementAmount: profile.pageIncrementAmount,
                useProgressSlider: profile.useProgressSlider,
                showSliderButtons: profile.showSliderButtons,
                useCircularProgressWatch: profile.useCircularProgressWatch,
                enableWatchPositionMarking: profile.enableWatchPositionMarking,
                hideAutoSessionsIPhone: profile.hideAutoSessionsIPhone,
                hideAutoSessionsWatch: profile.hideAutoSessionsWatch,
                showSettingsOnWatch: profile.showSettingsOnWatch,
                autoEndSessionEnabled: profile.autoEndSessionEnabled,
                autoEndSessionHours: profile.autoEndSessionHours,
                streakReminderEnabled: profile.streakReminderEnabled,
                streakReminderHour: profile.streakReminderHour,
                streakReminderMinute: profile.streakReminderMinute,
                streakReminderRespectFocus: profile.streakReminderRespectFocus,
                chartTypeRawValue: profile.chartTypeRawValue,
                heatmapPeriodRawValue: profile.heatmapPeriodRawValue,
                homeCardOrder: profile.homeCardOrder,
                bookDetailSectionOrder: profile.bookDetailSectionOrder
            )
        }

        let payload = ExportPayload(
            exportedAt: Date(),
            appVersion: Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "0.0",
            buildNumber: Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "0",
            profile: exportProfile,
            books: books.map { book in
                ExportBook(
                    id: book.id.uuidString,
                    title: book.title,
                    author: book.author,
                    isbn: book.isbn,
                    coverImageURL: book.coverImageURL?.absoluteString,
                    totalPages: book.totalPages,
                    currentPage: book.currentPage,
                    savedCurrentPage: book.savedCurrentPage,
                    bookTypeRawValue: book.bookTypeRawValue,
                    readingStatusRawValue: book.readingStatusRawValue,
                    dateAdded: book.dateAdded,
                    dateStarted: book.dateStarted,
                    dateFinished: book.dateFinished,
                    notes: book.notes,
                    rating: book.rating,
                    goodreadsShelves: book.goodreadsShelves,
                    bookDescription: book.bookDescription,
                    subjects: book.subjects,
                    publisher: book.publisher,
                    publishedDate: book.publishedDate,
                    language: book.language,
                    openLibraryWorkID: book.openLibraryWorkID,
                    openLibraryEditionID: book.openLibraryEditionID
                )
            },
            sessions: sessions.map { session in
                ExportSession(
                    id: session.id.uuidString,
                    bookId: session.book?.id.uuidString,
                    startDate: session.startDate,
                    endDate: session.endDate,
                    startPage: session.startPage,
                    endPage: session.endPage,
                    durationMinutes: session.durationMinutes,
                    xpEarned: session.xpEarned,
                    isAutoGenerated: session.isAutoGenerated,
                    countsTowardStats: session.countsTowardStats,
                    isImported: session.isImported,
                    xpAwarded: session.xpAwarded
                )
            },
            goals: goals.map { goal in
                ExportGoal(
                    id: goal.id.uuidString,
                    typeRawValue: goal.typeRawValue,
                    targetValue: goal.targetValue,
                    currentValue: goal.currentValue,
                    startDate: goal.startDate,
                    endDate: goal.endDate,
                    isCompleted: goal.isCompleted,
                    createdAt: goal.createdAt
                )
            },
            quotes: quotes.map { quote in
                ExportQuote(
                    id: quote.id.uuidString,
                    bookId: quote.book?.id.uuidString,
                    text: quote.text,
                    pageNumber: quote.pageNumber,
                    dateAdded: quote.dateAdded,
                    note: quote.note,
                    isFavorite: quote.isFavorite
                )
            },
            positions: positions.map { position in
                ExportPosition(
                    id: position.id.uuidString,
                    bookId: position.book?.id.uuidString,
                    pageNumber: position.pageNumber,
                    lineNumber: position.lineNumber,
                    timestamp: position.timestamp,
                    note: position.note
                )
            },
            achievements: achievements.map { achievement in
                ExportAchievement(
                    id: achievement.id.uuidString,
                    typeRawValue: achievement.typeRawValue,
                    unlockedAt: achievement.unlockedAt,
                    isNew: achievement.isNew
                )
            },
            streakEvents: streakEvents.map { event in
                ExportStreakEvent(
                    id: event.id.uuidString,
                    date: event.date,
                    typeRawValue: event.typeRawValue,
                    streakLength: event.streakLength
                )
            },
            activeSessions: activeSessions.map { active in
                ExportActiveSession(
                    id: active.id.uuidString,
                    bookId: active.book?.id.uuidString,
                    startDate: active.startDate,
                    currentPage: active.currentPage,
                    startPage: active.startPage,
                    isPaused: active.isPaused,
                    pausedAt: active.pausedAt,
                    totalPausedDuration: active.totalPausedDuration,
                    lastUpdated: active.lastUpdated,
                    sourceDevice: active.sourceDevice
                )
            }
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(payload)

        let filename = "Shlf-Export-\(timestampString()).json"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        try data.write(to: url, options: [.atomic])
        return url
    }

    private static func timestampString() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd-HHmmss"
        return formatter.string(from: Date())
    }
}
