//
//  WatchConnectivityManager.swift
//  Shlf
//
//  Created by João Fernandes on 28/11/2025.
//

import Foundation
import WatchConnectivity
import SwiftData
import OSLog

extension Notification.Name {
    static let watchReachabilityDidChange = Notification.Name("watchReachabilityDidChange")
    static let watchSessionReceived = Notification.Name("watchSessionReceived")
    static let watchStatsUpdated = Notification.Name("watchStatsUpdated")
}

private enum ReadingConstants {
    static let defaultMaxPages = 1000
}

class WatchConnectivityManager: NSObject {
    static let shared = WatchConnectivityManager()
    static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "com.shlf.app", category: "WatchSync")

    private var modelContext: ModelContext?
    private var lastActiveSessionEndDate: Date?
    private var endedActiveSessionIDs: [UUID: Date] = [:] // Track UUID -> timestamp when ended
    private var lastLiveActivityStateTimestamp: Date?

    private override init() {
        super.init()

        // Schedule periodic cleanup of old endedActiveSessionIDs (every hour)
        Timer.scheduledTimer(withTimeInterval: 3600, repeats: true) { [weak self] _ in
            self?.cleanupOldEndedSessionIDs()
        }
    }

    func configure(modelContext: ModelContext) {
        self.modelContext = modelContext
    }

    /// Cleanup old ended session IDs (older than 24 hours) to prevent unbounded memory growth
    private func cleanupOldEndedSessionIDs() {
        let threshold = Date().addingTimeInterval(-24 * 3600) // 24 hours ago
        let oldCount = endedActiveSessionIDs.count

        endedActiveSessionIDs = endedActiveSessionIDs.filter { _, timestamp in
            timestamp > threshold
        }

        let removedCount = oldCount - endedActiveSessionIDs.count
        if removedCount > 0 {
            Self.logger.info("🧹 Cleaned up \(removedCount) old ended session IDs (kept \(self.endedActiveSessionIDs.count))")
        }
    }

    // Fallback for background WC events when the app hasn't configured the context yet
    @MainActor
    private func resolvedModelContext() -> ModelContext? {
        if let modelContext {
            return modelContext
        }
        if let container = try? SwiftDataConfig.createModelContainer() {
            let ctx = container.mainContext
            self.modelContext = ctx
            return ctx
        }
        return nil
    }

    func activate() {
        guard WCSession.isSupported() else { return }
        let session = WCSession.default
        session.delegate = self
        session.activate()
        Self.logger.info("WatchConnectivity activated on iPhone")
    }

    func sendPageDeltaToWatch(bookUUID: UUID, delta: Int) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        do {
            let pageDelta = PageDelta(bookUUID: bookUUID, delta: delta)
            let data = try JSONEncoder().encode(pageDelta)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["pageDelta": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("❌ sendMessage failed: \(error.localizedDescription)")
                        // Automatic fallback to guaranteed delivery
                        WCSession.default.transferUserInfo(["pageDelta": data])
                        Self.logger.info("↩️ Auto-fallback: Queued page delta for guaranteed delivery")
                    }
                )
                Self.logger.info("📤 Sent page delta (instant): \(delta)")
            } else {
                WCSession.default.transferUserInfo(["pageDelta": data])
                Self.logger.info("📦 Queued page delta (guaranteed): \(delta)")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendSessionToWatch(_ session: ReadingSession) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard let bookId = session.book?.id else {
            Self.logger.warning("Cannot send session without book")
            return
        }

        do {
            let transfer = SessionTransfer(
                id: session.id,
                bookId: bookId,
                startDate: session.startDate,
                endDate: session.endDate,
                startPage: session.startPage,
                endPage: session.endPage,
                durationMinutes: session.durationMinutes,
                xpEarned: session.xpEarned,
                isAutoGenerated: session.isAutoGenerated
            )

            let data = try JSONEncoder().encode(transfer)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["session": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("Failed to send session to Watch: \(error)")
                    }
                )
                Self.logger.info("Sent session to Watch: \(session.pagesRead) pages")
            } else {
                WCSession.default.transferUserInfo(["session": data])
                Self.logger.info("Queued session to Watch: \(session.pagesRead) pages")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendActiveSessionUpdateToWatch(_ activeSession: ActiveReadingSession) {
        sendActiveSessionToWatch(activeSession)
    }

    func sendProfileSettingsToWatch(_ profile: UserProfile) {
        guard WCSession.default.activationState == .activated else { return }

        do {
            let transfer = ProfileSettingsTransfer(
                hideAutoSessionsIPhone: profile.hideAutoSessionsIPhone,
                hideAutoSessionsWatch: profile.hideAutoSessionsWatch,
                showSettingsOnWatch: profile.showSettingsOnWatch,
                useCircularProgressWatch: profile.useCircularProgressWatch,
                themeColorRawValue: profile.themeColorRawValue
            )
            let data = try JSONEncoder().encode(transfer)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["profileSettings": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("Failed to send profile settings: \(error)")
                    }
                )
                Self.logger.info("Sent profile settings to Watch")
            } else {
                WCSession.default.transferUserInfo(["profileSettings": data])
                Self.logger.info("Queued profile settings to Watch")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendProfileStatsToWatch(_ profile: UserProfile) {
        guard WCSession.default.activationState == .activated else { return }

        do {
            let transfer = ProfileStatsTransfer(
                totalXP: profile.totalXP,
                currentStreak: profile.currentStreak,
                longestStreak: profile.longestStreak,
                lastReadingDate: profile.lastReadingDate
            )
            let data = try JSONEncoder().encode(transfer)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["profileStats": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("❌ sendMessage failed: \(error.localizedDescription)")
                        // Automatic fallback to guaranteed delivery
                        WCSession.default.transferUserInfo(["profileStats": data])
                        Self.logger.info("↩️ Auto-fallback: Queued profile stats")
                    }
                )
                Self.logger.info("📤 Sent profile stats (instant): XP=\(profile.totalXP)")
            } else {
                WCSession.default.transferUserInfo(["profileStats": data])
                Self.logger.info("📦 Queued profile stats (guaranteed): XP=\(profile.totalXP)")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendActiveSessionToWatch(_ activeSession: ActiveReadingSession) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard let bookId = activeSession.book?.id else {
            Self.logger.warning("Cannot send active session without book")
            return
        }

        do {
            let transfer = ActiveSessionTransfer(
                id: activeSession.id,
                bookId: bookId,
                startDate: activeSession.startDate,
                currentPage: activeSession.currentPage,
                startPage: activeSession.startPage,
                isPaused: activeSession.isPaused,
                pausedAt: activeSession.pausedAt,
                totalPausedDuration: activeSession.totalPausedDuration,
                lastUpdated: activeSession.lastUpdated,
                sourceDevice: activeSession.sourceDevice
            )

            let data = try JSONEncoder().encode(transfer)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["activeSession": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("❌ sendMessage failed: \(error.localizedDescription)")
                        WCSession.default.transferUserInfo(["activeSession": data])
                        Self.logger.info("↩️ Auto-fallback: Queued active session")
                    }
                )
                Self.logger.info("📤 Sent active session (instant): \(activeSession.pagesRead) pages")
            } else {
                WCSession.default.transferUserInfo(["activeSession": data])
                Self.logger.info("📦 Queued active session (guaranteed): \(activeSession.pagesRead) pages")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendActiveSessionEndToWatch(activeSessionId: UUID? = nil) {
        guard WCSession.default.activationState == .activated else { return }

        var payload: [String: Any] = ["activeSessionEnd": true]
        if let id = activeSessionId {
            payload["activeSessionEndId"] = id.uuidString
            endedActiveSessionIDs[id] = Date()
        }

        // Use transferUserInfo so the end signal always lands and doesn't block UI
        WCSession.default.transferUserInfo(payload)
        Self.logger.info("📦 Queued active session end (guaranteed)")
    }

    /// Sends a consolidated session completion message to Watch (ATOMIC - replaces separate messages)
    /// Combines activeSessionEnd, completedSession, and liveActivityEnd into a single atomic transfer
    func sendSessionCompletionToWatch(activeSessionId: UUID, completedSession: ReadingSession) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard let bookId = completedSession.book?.id else {
            Self.logger.warning("Session has no book")
            return
        }

        do {
            let sessionTransfer = SessionTransfer(
                id: completedSession.id,
                bookId: bookId,
                startDate: completedSession.startDate,
                endDate: completedSession.endDate,
                startPage: completedSession.startPage,
                endPage: completedSession.endPage,
                durationMinutes: completedSession.durationMinutes,
                xpEarned: completedSession.xpEarned,
                isAutoGenerated: completedSession.isAutoGenerated
            )

            let completion = SessionCompletionTransfer(
                activeSessionId: activeSessionId,
                completedSession: sessionTransfer,
                endLiveActivity: true
            )

            let data = try JSONEncoder().encode(completion)

            // ALWAYS use transferUserInfo for session completion to guarantee atomic delivery
            WCSession.default.transferUserInfo(["sessionCompletion": data])
            endedActiveSessionIDs[activeSessionId] = Date()

            Self.logger.info("📦 Queued session completion to Watch (atomic): \(completedSession.endPage - completedSession.startPage) pages, \(completedSession.xpEarned) XP")
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendBookPositionToWatch(_ position: BookPosition) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard let bookId = position.book?.id else {
            Self.logger.warning("Cannot send position without book")
            return
        }

        do {
            let transfer = BookPositionTransfer(
                id: position.id,
                bookId: bookId,
                pageNumber: position.pageNumber,
                lineNumber: position.lineNumber,
                timestamp: position.timestamp,
                note: position.note
            )

            let data = try JSONEncoder().encode(transfer)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["bookPosition": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("Failed to send position to Watch: \(error)")
                    }
                )
                Self.logger.info("Sent position to Watch: Page \(position.pageNumber)")
            } else {
                WCSession.default.transferUserInfo(["bookPosition": data])
                Self.logger.info("Queued position to Watch: Page \(position.pageNumber)")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    func sendQuotesToWatch(for book: Book) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard let quotes = book.quotes, !quotes.isEmpty else {
            Self.logger.info("No quotes to send for book")
            return
        }

        do {
            let transfers = quotes.map { quote in
                QuoteTransfer(
                    id: quote.id,
                    bookId: book.id,
                    text: quote.text,
                    pageNumber: quote.pageNumber,
                    dateAdded: quote.dateAdded,
                    note: quote.note,
                    isFavorite: quote.isFavorite
                )
            }

            let data = try JSONEncoder().encode(transfers)
            if WCSession.default.isReachable {
                WCSession.default.sendMessage(
                    ["quotes": data],
                    replyHandler: nil,
                    errorHandler: { error in
                        Self.logger.error("Failed to send quotes to Watch: \(error)")
                    }
                )
                Self.logger.info("Sent \(quotes.count) quotes to Watch")
            } else {
                WCSession.default.transferUserInfo(["quotes": data])
                Self.logger.info("Queued \(quotes.count) quotes to Watch")
            }
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    @MainActor
    func syncBooksToWatch() async {
        guard WCSession.default.activationState == .activated,
              let modelContext = modelContext else {
            Self.logger.warning("Cannot sync - WC not activated or context not configured")
            return
        }

        do {
            // Fetch all currently reading books
            let booksDescriptor = FetchDescriptor<Book>(
                sortBy: [SortDescriptor(\.title)]
            )
            let allBooks = try modelContext.fetch(booksDescriptor)
            let currentlyReading = allBooks.filter { $0.readingStatus == .currentlyReading }

            Self.logger.info("Syncing \(currentlyReading.count) books to Watch...")

            // Convert books to transferable format
            let bookTransfers = currentlyReading.map { book in
                BookTransfer(
                    id: book.id,
                    title: book.title,
                    author: book.author,
                    isbn: book.isbn,
                    coverImageURL: book.coverImageURL?.absoluteString,
                    totalPages: book.totalPages,
                    currentPage: book.currentPage,
                    bookTypeRawValue: book.bookTypeRawValue,
                    readingStatusRawValue: book.readingStatusRawValue,
                    dateAdded: book.dateAdded,
                    notes: book.notes
                )
            }

            // Fetch sessions for currently reading books
            let bookIds = currentlyReading.map { $0.id }
            let sessionsDescriptor = FetchDescriptor<ReadingSession>(
                sortBy: [SortDescriptor(\.startDate, order: .reverse)]
            )
            let allSessions = try modelContext.fetch(sessionsDescriptor)
            let relevantSessions = allSessions.filter { session in
                guard let book = session.book else { return false }
                return bookIds.contains(book.id)
            }

            Self.logger.info("Syncing \(relevantSessions.count) sessions to Watch...")

            // Convert sessions to transferable format
            let sessionTransfers = relevantSessions.compactMap { session -> SessionTransfer? in
                guard let bookId = session.book?.id else { return nil }
                return SessionTransfer(
                    id: session.id,
                    bookId: bookId,
                    startDate: session.startDate,
                    endDate: session.endDate,
                    startPage: session.startPage,
                    endPage: session.endPage,
                    durationMinutes: session.durationMinutes,
                    xpEarned: session.xpEarned,
                    isAutoGenerated: session.isAutoGenerated
                )
            }

            let booksData = try JSONEncoder().encode(bookTransfers)
            let sessionsData = try JSONEncoder().encode(sessionTransfers)

            // Use updateApplicationContext for guaranteed delivery
            try WCSession.default.updateApplicationContext([
                "books": booksData,
                "sessions": sessionsData
            ])
            Self.logger.info("Sent \(bookTransfers.count) books and \(sessionTransfers.count) sessions to Watch")
        } catch {
            Self.logger.error("Failed to sync to Watch: \(error)")
        }
    }
}

extension WatchConnectivityManager: WCSessionDelegate {
    nonisolated func session(
        _ session: WCSession,
        activationDidCompleteWith activationState: WCSessionActivationState,
        error: Error?
    ) {
        if let error = error {
            Self.logger.error("WC activation error: \(error)")
        } else {
            Self.logger.info("WC activated: \(activationState.rawValue)")
            // Sync books to watch when activated
            Task { @MainActor in
                await WatchConnectivityManager.shared.syncBooksToWatch()
            }
        }
    }

    nonisolated func sessionDidBecomeInactive(_ session: WCSession) {
        Self.logger.warning("WC session became inactive")
    }

    nonisolated func sessionDidDeactivate(_ session: WCSession) {
        Self.logger.warning("WC session deactivated")
        // Reactivate session for new watch
        session.activate()
    }

    nonisolated func sessionReachabilityDidChange(_ session: WCSession) {
        NotificationCenter.default.post(name: .watchReachabilityDidChange, object: nil)
    }

    nonisolated func session(
        _ session: WCSession,
        didReceiveMessage message: [String: Any]
    ) {
        Self.logger.info("iPhone received message")

        // Handle page delta
        if let pageDeltaData = message["pageDelta"] as? Data {
            Task { @MainActor in
                do {
                    let delta = try JSONDecoder().decode(PageDelta.self, from: pageDeltaData)
                    Self.logger.info("Received page delta: \(delta.delta) for book")
                    await self.handlePageDelta(delta)
                } catch {
                    Self.logger.error("Page delta decoding error: \(error)")
                }
            }
        }

        // Handle session from Watch
        if let sessionData = message["session"] as? Data {
            Task { @MainActor in
                do {
                    let sessionTransfer = try JSONDecoder().decode(SessionTransfer.self, from: sessionData)
                    Self.logger.info("Received session from Watch: \(sessionTransfer.endPage - sessionTransfer.startPage) pages")
                    await self.handleWatchSession(sessionTransfer)
                } catch {
                    Self.logger.error("Session decoding error: \(error)")
                }
            }
        }

        // Handle profile settings from Watch
        if let profileData = message["profileSettings"] as? Data {
            Task { @MainActor in
                do {
                    let settings = try JSONDecoder().decode(ProfileSettingsTransfer.self, from: profileData)
                    Self.logger.info("Received profile settings from Watch")
                    await self.handleProfileSettings(settings)
                } catch {
                    Self.logger.error("Profile settings decoding error: \(error)")
                }
            }
        }

        // Handle profile stats from Watch
        if let statsData = message["profileStats"] as? Data {
            Task { @MainActor in
                do {
                    let stats = try JSONDecoder().decode(ProfileStatsTransfer.self, from: statsData)
                    Self.logger.info("Received profile stats from Watch: XP=\(stats.totalXP), Streak=\(stats.currentStreak)")
                    await self.handleProfileStats(stats)
                } catch {
                    Self.logger.error("Profile stats decoding error: \(error)")
                }
            }
        }

        // Handle Live Activity start from Watch
        if let liveActivityData = message["liveActivityStart"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityStartTransfer.self, from: liveActivityData)
                    Self.logger.info("Received Live Activity start from Watch: \(transfer.bookTitle)")
                    await self.handleLiveActivityStart(transfer)
                } catch {
                    Self.logger.error("Live Activity start decoding error: \(error)")
                }
            }
        }

        // Handle Live Activity update from Watch
        if let liveActivityData = message["liveActivityUpdate"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityUpdateTransfer.self, from: liveActivityData)
                    await self.handleLiveActivityUpdate(transfer)
                } catch {
                    Self.logger.error("Live Activity update decoding error: \(error)")
                }
            }
        }

        // Handle Live Activity state change from Watch
        if let liveActivityData = message["liveActivityState"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityStateTransfer.self, from: liveActivityData)
                    await self.handleLiveActivityState(transfer)
                } catch {
                    Self.logger.error("Live Activity state decoding error: \(error)")
                }
            }
        }

        // Handle Live Activity end from Watch
        if message["liveActivityEnd"] != nil {
            Task { @MainActor in
                await self.handleLiveActivityEnd()
            }
        }

        // Handle active session from Watch
        if let activeSessionData = message["activeSession"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(ActiveSessionTransfer.self, from: activeSessionData)
                    Self.logger.info("Received active session from Watch: \(transfer.pagesRead) pages")
                    await self.handleActiveSession(transfer)
                } catch {
                    Self.logger.error("Active session decoding error: \(error)")
                }
            }
        }

        // Handle active session end from Watch
        if message["activeSessionEnd"] != nil {
            Task { @MainActor in
                let idString = message["activeSessionEndId"] as? String
                await self.handleActiveSessionEnd(endedId: idString.flatMap(UUID.init))
            }
        }

        // ✅ Handle consolidated session completion from Watch (PREFERRED)
        if let completionData = message["sessionCompletion"] as? Data {
            Task { @MainActor in
                do {
                    let completion = try JSONDecoder().decode(SessionCompletionTransfer.self, from: completionData)
                    Self.logger.info("✅ Received atomic session completion from Watch: \(completion.completedSession.endPage - completion.completedSession.startPage) pages")
                    await self.handleSessionCompletion(completion)
                } catch {
                    Self.logger.error("Session completion decoding error: \(error)")
                }
            }
        }

        // Handle book position from Watch
        if let positionData = message["bookPosition"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(BookPositionTransfer.self, from: positionData)
                    Self.logger.info("Received book position from Watch: Page \(transfer.pageNumber)")
                    await self.handleBookPosition(transfer)
                } catch {
                    Self.logger.error("Book position decoding error: \(error)")
                }
            }
        }

        // Handle quotes from Watch
        if let quotesData = message["quotes"] as? Data {
            Task { @MainActor in
                do {
                    let transfers = try JSONDecoder().decode([QuoteTransfer].self, from: quotesData)
                    Self.logger.info("Received \(transfers.count) quotes from Watch")
                    await self.handleQuotes(transfers)
                } catch {
                    Self.logger.error("Quotes decoding error: \(error)")
                }
            }
        }
    }

    nonisolated func session(_ session: WCSession, didReceiveUserInfo userInfo: [String: Any]) {
        Self.logger.info("iPhone received userInfo payload")

        if let pageDeltaData = userInfo["pageDelta"] as? Data {
            Task { @MainActor in
                do {
                    let delta = try JSONDecoder().decode(PageDelta.self, from: pageDeltaData)
                    Self.logger.info("Received queued page delta: \(delta.delta)")
                    await self.handlePageDelta(delta)
                } catch {
                    Self.logger.error("Page delta userInfo decoding error: \(error)")
                }
            }
        }

        if let sessionData = userInfo["session"] as? Data {
            Task { @MainActor in
                do {
                    let sessionTransfer = try JSONDecoder().decode(SessionTransfer.self, from: sessionData)
                    Self.logger.info("Received queued session from Watch: \(sessionTransfer.endPage - sessionTransfer.startPage) pages")
                    await self.handleWatchSession(sessionTransfer)
                } catch {
                    Self.logger.error("Session userInfo decoding error: \(error)")
                }
            }
        }

        if let profileData = userInfo["profileSettings"] as? Data {
            Task { @MainActor in
                do {
                    let settings = try JSONDecoder().decode(ProfileSettingsTransfer.self, from: profileData)
                    Self.logger.info("Received queued profile settings from Watch")
                    await self.handleProfileSettings(settings)
                } catch {
                    Self.logger.error("Profile settings userInfo decoding error: \(error)")
                }
            }
        }

        if let statsData = userInfo["profileStats"] as? Data {
            Task { @MainActor in
                do {
                    let stats = try JSONDecoder().decode(ProfileStatsTransfer.self, from: statsData)
                    Self.logger.info("Received queued profile stats from Watch: XP=\(stats.totalXP), Streak=\(stats.currentStreak)")
                    await self.handleProfileStats(stats)
                } catch {
                    Self.logger.error("Profile stats userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued Live Activity start from Watch
        if let liveActivityData = userInfo["liveActivityStart"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityStartTransfer.self, from: liveActivityData)
                    Self.logger.info("📦 Received queued Live Activity start from Watch: \(transfer.bookTitle)")
                    await self.handleLiveActivityStart(transfer)
                } catch {
                    Self.logger.error("Live Activity start userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued Live Activity update from Watch
        if let liveActivityData = userInfo["liveActivityUpdate"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityUpdateTransfer.self, from: liveActivityData)
                    await self.handleLiveActivityUpdate(transfer)
                } catch {
                    Self.logger.error("Live Activity update userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued Live Activity state change from Watch
        if let liveActivityData = userInfo["liveActivityState"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(LiveActivityStateTransfer.self, from: liveActivityData)
                    await self.handleLiveActivityState(transfer)
                } catch {
                    Self.logger.error("Live Activity state userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued Live Activity end from Watch
        if userInfo["liveActivityEnd"] != nil {
            Task { @MainActor in
                await self.handleLiveActivityEnd()
            }
        }

        // Handle queued active session from Watch
        if let activeSessionData = userInfo["activeSession"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(ActiveSessionTransfer.self, from: activeSessionData)
                    Self.logger.info("📦 Received queued active session from Watch: \(transfer.pagesRead) pages")
                    await self.handleActiveSession(transfer)
                } catch {
                    Self.logger.error("Active session userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued active session end from Watch
        if userInfo["activeSessionEnd"] != nil {
            Task { @MainActor in
                let idString = userInfo["activeSessionEndId"] as? String
                await self.handleActiveSessionEnd(endedId: idString.flatMap(UUID.init))
            }
        }

        // ✅ Handle queued consolidated session completion from Watch (PREFERRED)
        if let completionData = userInfo["sessionCompletion"] as? Data {
            Task { @MainActor in
                do {
                    let completion = try JSONDecoder().decode(SessionCompletionTransfer.self, from: completionData)
                    Self.logger.info("✅📦 Received queued atomic session completion from Watch: \(completion.completedSession.endPage - completion.completedSession.startPage) pages")
                    await self.handleSessionCompletion(completion)
                } catch {
                    Self.logger.error("Session completion userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued book position from Watch
        if let positionData = userInfo["bookPosition"] as? Data {
            Task { @MainActor in
                do {
                    let transfer = try JSONDecoder().decode(BookPositionTransfer.self, from: positionData)
                    Self.logger.info("📦 Received queued book position from Watch: Page \(transfer.pageNumber)")
                    await self.handleBookPosition(transfer)
                } catch {
                    Self.logger.error("Book position userInfo decoding error: \(error)")
                }
            }
        }

        // Handle queued quotes from Watch
        if let quotesData = userInfo["quotes"] as? Data {
            Task { @MainActor in
                do {
                    let transfers = try JSONDecoder().decode([QuoteTransfer].self, from: quotesData)
                    Self.logger.info("📦 Received queued \(transfers.count) quotes from Watch")
                    await self.handleQuotes(transfers)
                } catch {
                    Self.logger.error("Quotes userInfo decoding error: \(error)")
                }
            }
        }
    }

    @MainActor
    private func handlePageDelta(_ delta: PageDelta) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Fetch the book by UUID
            let descriptor = FetchDescriptor<Book>(
                predicate: #Predicate<Book> { book in
                    book.id == delta.bookUUID
                }
            )
            let books = try modelContext.fetch(descriptor)

            guard let book = books.first else {
                Self.logger.warning("Book not found with UUID: \(delta.bookUUID)")
                return
            }

            // Update current page
            book.currentPage = min((book.totalPages ?? ReadingConstants.defaultMaxPages), book.currentPage + delta.delta)

            // Save context
            try modelContext.save()

            Self.logger.info("Updated book: \(book.title) to page \(book.currentPage)")

            // Update Live Activity if running
            await ReadingSessionActivityManager.shared.updateCurrentPage(book.currentPage)

            // Refresh widget with updated progress
            WidgetDataExporter.exportSnapshot(modelContext: modelContext)
        } catch {
            Self.logger.error("Failed to update book: \(error)")
        }
    }

    @MainActor
    private func handleWatchSession(_ transfer: SessionTransfer) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            let engine = GamificationEngine(modelContext: modelContext)
            let sessionDate = transfer.endDate ?? transfer.startDate

            // Track XP difference if updating
            var xpDelta = 0
            var xpForActivity = 0

            // Check if session already exists
            let descriptor = FetchDescriptor<ReadingSession>(
                predicate: #Predicate<ReadingSession> { session in
                    session.id == transfer.id
                }
            )
            let existingSessions = try modelContext.fetch(descriptor)

            var bookForSession: Book?

            if let existingSession = existingSessions.first {
                // Update existing session
                let previousXP = existingSession.xpEarned
                existingSession.startDate = transfer.startDate
                existingSession.endDate = transfer.endDate
                existingSession.startPage = transfer.startPage
                existingSession.endPage = transfer.endPage
                existingSession.durationMinutes = transfer.durationMinutes
                existingSession.xpEarned = engine.calculateXP(for: existingSession)
                existingSession.isAutoGenerated = transfer.isAutoGenerated
                bookForSession = existingSession.book
                xpDelta = existingSession.xpEarned - previousXP
                xpForActivity = existingSession.xpEarned
                Self.logger.info("Updated existing session from Watch")
            } else {
                // Find the book
                let bookDescriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { book in
                        book.id == transfer.bookId
                    }
                )
                let books = try modelContext.fetch(bookDescriptor)

                guard let book = books.first else {
                    Self.logger.warning("Book not found for Watch session: \(transfer.bookId)")
                    return
                }

                // Create new session
                let session = ReadingSession(
                    id: transfer.id,
                    startDate: transfer.startDate,
                    endDate: transfer.endDate,
                    startPage: transfer.startPage,
                    endPage: transfer.endPage,
                    durationMinutes: transfer.durationMinutes,
                    xpEarned: 0,
                    isAutoGenerated: transfer.isAutoGenerated,
                    book: book
                )
                session.xpEarned = engine.calculateXP(for: session)
                modelContext.insert(session)
                bookForSession = book
                xpDelta = session.xpEarned
                xpForActivity = session.xpEarned
                Self.logger.info("Created new session from Watch: \(transfer.endPage - transfer.startPage) pages, \(session.xpEarned) XP")
            }

            // Align book progress to session
            if let book = bookForSession {
                let maxPages = book.totalPages ?? ReadingConstants.defaultMaxPages
                book.currentPage = min(maxPages, max(0, transfer.endPage))
                await ReadingSessionActivityManager.shared.updateActivity(
                    currentPage: book.currentPage,
                    xpEarned: xpForActivity
                )
            }

            try modelContext.save()

            // Update profile stats with authoritative calculation
            let profileDescriptor = FetchDescriptor<UserProfile>()
            if let profile = try modelContext.fetch(profileDescriptor).first {
                if xpDelta != 0 {
                    engine.awardXP(xpDelta, to: profile)
                }
                engine.updateStreak(for: profile, sessionDate: sessionDate)
                engine.checkAchievements(for: profile)
                try modelContext.save()
                WidgetDataExporter.exportSnapshot(modelContext: modelContext)
                // Keep Watch in sync with latest stats
                sendProfileStatsToWatch(profile)
            }

            // Force UI refresh
            NotificationCenter.default.post(name: .watchSessionReceived, object: nil)

            // If this session has an end date, end Live Activity to avoid stale state
            if transfer.endDate != nil {
                await ReadingSessionActivityManager.shared.endActivity()
                WidgetDataExporter.exportSnapshot(modelContext: modelContext)
            } else {
                await ReadingSessionActivityManager.shared.updateActivity(
                    currentPage: transfer.endPage,
                    xpEarned: xpForActivity
                )
            }
        } catch {
            Self.logger.error("Failed to handle Watch session: \(error)")
        }
    }

    @MainActor
    private func handleProfileSettings(_ settings: ProfileSettingsTransfer) async {
        guard let modelContext = modelContext else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            let descriptor = FetchDescriptor<UserProfile>()
            let profiles = try modelContext.fetch(descriptor)

            if let profile = profiles.first {
                profile.hideAutoSessionsIPhone = settings.hideAutoSessionsIPhone
                profile.hideAutoSessionsWatch = settings.hideAutoSessionsWatch
                profile.showSettingsOnWatch = settings.showSettingsOnWatch
                profile.useCircularProgressWatch = settings.useCircularProgressWatch
                profile.themeColorRawValue = settings.themeColorRawValue
                try modelContext.save()
                Self.logger.info("Updated profile settings from Watch")
            }
        } catch {
            Self.logger.error("Failed to update profile settings: \(error)")
        }
    }

    @MainActor
    private func handleProfileStats(_ stats: ProfileStatsTransfer) async {
        guard let modelContext = modelContext else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            let descriptor = FetchDescriptor<UserProfile>()
            let profiles = try modelContext.fetch(descriptor)

            if let profile = profiles.first {
                profile.totalXP = stats.totalXP
                profile.currentStreak = stats.currentStreak
                profile.longestStreak = stats.longestStreak
                profile.lastReadingDate = stats.lastReadingDate
                try modelContext.save()
                Self.logger.info("Updated profile stats from Watch: XP=\(stats.totalXP), Streak=\(stats.currentStreak)")

                // Refresh widget with updated stats
                WidgetDataExporter.exportSnapshot(modelContext: modelContext)

                // Force UI refresh
                NotificationCenter.default.post(name: .watchStatsUpdated, object: nil)
            }
        } catch {
            Self.logger.error("Failed to update profile stats: \(error)")
        }
    }

    // MARK: - Live Activity Handlers

    @MainActor
    private func handleLiveActivityStart(_ transfer: LiveActivityStartTransfer) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Prefer stable book ID; fall back to title if missing
            var book: Book?
            if let bookId = transfer.bookId {
                let descriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { $0.id == bookId }
                )
                book = try modelContext.fetch(descriptor).first
            }

            if book == nil {
                let descriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { $0.title == transfer.bookTitle }
                )
                book = try modelContext.fetch(descriptor).first
            }

            guard let book else {
                Self.logger.warning("Book not found for Live Activity: \(transfer.bookTitle)")
                return
            }

            // Get theme color from profile
            let profileDescriptor = FetchDescriptor<UserProfile>()
            let profile = try? modelContext.fetch(profileDescriptor).first
            let themeHex = profile?.themeColor.color.toHex() ?? "#00CED1"

            // Start Live Activity with the authoritative baseline from Watch
            await ReadingSessionActivityManager.shared.startActivity(
                book: book,
                currentPage: transfer.currentPage,
                startPage: transfer.startPage,
                startTime: transfer.startTime,
                themeColorHex: themeHex
            )
            Self.logger.info("✅ Started Live Activity from Watch: \(transfer.bookTitle)")
        } catch {
            Self.logger.error("Failed to start Live Activity from Watch: \(error)")
        }
    }

    @MainActor
    private func handleLiveActivityUpdate(_ transfer: LiveActivityUpdateTransfer) async {
        await ReadingSessionActivityManager.shared.updateActivity(
            currentPage: transfer.currentPage,
            xpEarned: transfer.xpEarned
        )
        // Export widget snapshot so widgets/Dynamic Island reflect the latest page/XP
        if let modelContext = modelContext {
            WidgetDataExporter.exportSnapshot(modelContext: modelContext)
        }
        Self.logger.info("Updated Live Activity from Watch: Page \(transfer.currentPage)")
    }

    @MainActor
    private func handleLiveActivityState(_ transfer: LiveActivityStateTransfer) async {
        if let last = lastLiveActivityStateTimestamp, transfer.timestamp <= last {
            Self.logger.info("Ignoring stale Live Activity state update")
            return
        }

        lastLiveActivityStateTimestamp = transfer.timestamp

        if transfer.isPaused {
            await ReadingSessionActivityManager.shared.pauseActivity()
            Self.logger.info("⏸️ Paused Live Activity from Watch")
        } else {
            await ReadingSessionActivityManager.shared.resumeActivity()
            Self.logger.info("▶️ Resumed Live Activity from Watch")
        }
    }

    @MainActor
    private func handleLiveActivityEnd() async {
        await ReadingSessionActivityManager.shared.endActivity()
        if let modelContext = await resolvedModelContext() {
            WidgetDataExporter.exportSnapshot(modelContext: modelContext)
        }
        Self.logger.info("🛑 Ended Live Activity from Watch")
    }

    // MARK: - Active Session Handlers

    @MainActor
    private func handleActiveSession(_ transfer: ActiveSessionTransfer) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        if let lastEnd = lastActiveSessionEndDate, transfer.lastUpdated <= lastEnd {
            Self.logger.info("Ignoring stale active session update (ended at \(lastEnd))")
            return
        }

        if endedActiveSessionIDs[transfer.id] != nil {
            Self.logger.info("Ignoring active session update for ended id \(transfer.id)")
            return
        }

        do {
            // Fetch existing session
            let descriptor = FetchDescriptor<ActiveReadingSession>()
            let existingSessions = try modelContext.fetch(descriptor)

            if let existingSession = existingSessions.first {
                // Drop stale updates that arrive out of order
                if transfer.lastUpdated <= existingSession.lastUpdated {
                    Self.logger.info("Ignoring stale active session update from Watch (existing newer)")
                    return
                }

                // UPDATE in place - don't delete!
                existingSession.currentPage = transfer.currentPage
                existingSession.isPaused = transfer.isPaused
                existingSession.pausedAt = transfer.pausedAt
                existingSession.totalPausedDuration = transfer.totalPausedDuration
                existingSession.lastUpdated = transfer.lastUpdated
                existingSession.book?.currentPage = transfer.currentPage
                Self.logger.info("✅ Updated session from Watch: \(transfer.pagesRead) pages")

                // Force immediate widget update
                try? modelContext.save()
                WidgetDataExporter.exportSnapshot(modelContext: modelContext)
            } else {
                // Find the book
                let bookDescriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { book in
                        book.id == transfer.bookId
                    }
                )
                let books = try modelContext.fetch(bookDescriptor)

                guard let book = books.first else {
                    Self.logger.warning("Book not found: \(transfer.bookId)")
                    return
                }

                // Create NEW session only if none exists
                let activeSession = ActiveReadingSession(
                    id: transfer.id,
                    book: book,
                    startDate: transfer.startDate,
                    currentPage: transfer.currentPage,
                    startPage: transfer.startPage,
                    isPaused: transfer.isPaused,
                    pausedAt: transfer.pausedAt,
                    totalPausedDuration: transfer.totalPausedDuration,
                    lastUpdated: transfer.lastUpdated,
                    sourceDevice: transfer.sourceDevice
                )
                modelContext.insert(activeSession)
                // Clamp to max pages
                let maxPages = book.totalPages ?? ReadingConstants.defaultMaxPages
                book.currentPage = min(maxPages, transfer.currentPage)
                Self.logger.info("✅ Created session from Watch: \(transfer.pagesRead) pages")
            }

            // Update Live Activity FIRST (real-time)
            await ReadingSessionActivityManager.shared.updateActivity(
                currentPage: transfer.currentPage,
                xpEarned: 0
            )

            // Then save and update widgets (best-effort)
            try modelContext.save()
            WidgetDataExporter.exportSnapshot(modelContext: modelContext)

            // Post notification to update UI
            NotificationCenter.default.post(name: .watchSessionReceived, object: nil)
        } catch {
            Self.logger.error("Failed to handle active session: \(error)")
        }
    }

    @MainActor
    private func handleActiveSessionEnd(endedId: UUID? = nil) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Delete all active sessions
            let descriptor = FetchDescriptor<ActiveReadingSession>()
            let activeSessions = try modelContext.fetch(descriptor)

            for session in activeSessions {
                endedActiveSessionIDs[session.id] = Date()
                modelContext.delete(session)
            }

            try modelContext.save()
            Self.logger.info("Ended all active sessions from Watch")
            lastActiveSessionEndDate = Date()

            // Remember explicitly-ended id even if none existed locally
            if let endedId {
                endedActiveSessionIDs[endedId] = Date()
            }

            // End Live Activity and refresh widgets
            await ReadingSessionActivityManager.shared.endActivity()
            WidgetDataExporter.exportSnapshot(modelContext: modelContext)

            // Post notification to update UI
            NotificationCenter.default.post(name: .watchSessionReceived, object: nil)
        } catch {
            Self.logger.error("Failed to end active sessions: \(error)")
        }
    }

    /// Handles consolidated session completion from Watch (ATOMIC - replaces separate handling)
    @MainActor
    private func handleSessionCompletion(_ completion: SessionCompletionTransfer) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        Self.logger.info("🎯 Processing atomic session completion from Watch")

        // 1. End active session
        endedActiveSessionIDs[completion.activeSessionId] = Date()
        do {
            let descriptor = FetchDescriptor<ActiveReadingSession>(
                predicate: #Predicate<ActiveReadingSession> { session in
                    session.id == completion.activeSessionId
                }
            )
            let activeSessions = try modelContext.fetch(descriptor)
            for session in activeSessions {
                modelContext.delete(session)
                Self.logger.info("✅ Deleted active session: \(completion.activeSessionId)")
            }
        } catch {
            Self.logger.error("Failed to delete active session: \(error)")
        }

        // 2. Process completed session (includes ending Live Activity if session has endDate)
        await handleWatchSession(completion.completedSession)

        // 3. Export snapshot and notify UI
        WidgetDataExporter.exportSnapshot(modelContext: modelContext)
        NotificationCenter.default.post(name: .watchSessionReceived, object: nil)

        Self.logger.info("✅ Atomic session completion handled successfully")
    }

    @MainActor
    private func handleBookPosition(_ transfer: BookPositionTransfer) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Find the book
            let bookDescriptor = FetchDescriptor<Book>(
                predicate: #Predicate<Book> { book in
                    book.id == transfer.bookId
                }
            )
            let books = try modelContext.fetch(bookDescriptor)

            guard let book = books.first else {
                Self.logger.warning("Book not found for position: \(transfer.bookId)")
                return
            }

            // Create or update position
            let position = BookPosition(
                book: book,
                pageNumber: transfer.pageNumber,
                lineNumber: transfer.lineNumber,
                timestamp: transfer.timestamp,
                note: transfer.note
            )
            position.id = transfer.id

            modelContext.insert(position)

            if book.bookPositions == nil {
                book.bookPositions = []
            }
            book.bookPositions?.append(position)

            try modelContext.save()
            Self.logger.info("✅ Saved book position from Watch: Page \(transfer.pageNumber)")
        } catch {
            Self.logger.error("Failed to handle book position: \(error)")
        }
    }

    @MainActor
    private func handleQuotes(_ transfers: [QuoteTransfer]) async {
        guard let modelContext = await resolvedModelContext() else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            for transfer in transfers {
                // Find the book
                let bookDescriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { book in
                        book.id == transfer.bookId
                    }
                )
                let books = try modelContext.fetch(bookDescriptor)

                guard let book = books.first else {
                    Self.logger.warning("Book not found for quote: \(transfer.bookId)")
                    continue
                }

                // Create quote
                let quote = Quote(
                    book: book,
                    text: transfer.text,
                    pageNumber: transfer.pageNumber,
                    note: transfer.note,
                    isFavorite: transfer.isFavorite
                )
                quote.id = transfer.id
                quote.dateAdded = transfer.dateAdded

                modelContext.insert(quote)

                if book.quotes == nil {
                    book.quotes = []
                }
                book.quotes?.append(quote)
            }

            try modelContext.save()
            Self.logger.info("✅ Saved \(transfers.count) quotes from Watch")
        } catch {
            Self.logger.error("Failed to handle quotes: \(error)")
        }
    }
}
