//
//  WatchConnectivityManager.swift
//  Shlf
//
//  Created by João Fernandes on 28/11/2025.
//

import Foundation
import WatchConnectivity
import SwiftData
import OSLog

extension Notification.Name {
    nonisolated(unsafe) static let watchReachabilityDidChange = Notification.Name("watchReachabilityDidChange")
}

private enum ReadingConstants {
    static let defaultMaxPages = 1000
}

struct PageDelta: Codable, Sendable {
    let bookUUID: UUID
    let delta: Int
}

struct BookTransfer: Codable, Sendable {
    let id: UUID
    let title: String
    let author: String
    let isbn: String?
    let coverImageURL: String?
    let totalPages: Int?
    let currentPage: Int
    let bookTypeRawValue: String
    let readingStatusRawValue: String
    let dateAdded: Date
    let notes: String
}

struct SessionTransfer: Codable, Sendable {
    let id: UUID
    let bookId: UUID
    let startDate: Date
    let endDate: Date?
    let startPage: Int
    let endPage: Int
    let durationMinutes: Int
    let xpEarned: Int
    let isAutoGenerated: Bool
}

class WatchConnectivityManager: NSObject {
    static let shared = WatchConnectivityManager()
    nonisolated(unsafe) static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "com.shlf.app", category: "WatchSync")

    private var modelContext: ModelContext?

    private override init() {
        super.init()
    }

    func configure(modelContext: ModelContext) {
        self.modelContext = modelContext
    }

    func activate() {
        guard WCSession.isSupported() else { return }
        let session = WCSession.default
        session.delegate = self
        session.activate()
        Self.logger.info("WatchConnectivity activated on iPhone")
    }

    func sendPageDeltaToWatch(bookUUID: UUID, delta: Int) {
        guard WCSession.default.activationState == .activated else {
            Self.logger.warning("WC not activated")
            return
        }

        guard WCSession.default.isReachable else {
            Self.logger.info("Watch not reachable - delta will sync via context later")
            return
        }

        do {
            let pageDelta = PageDelta(bookUUID: bookUUID, delta: delta)
            let data = try JSONEncoder().encode(pageDelta)
            WCSession.default.sendMessage(
                ["pageDelta": data],
                replyHandler: nil,
                errorHandler: { error in
                    Self.logger.error("Failed to send page delta to Watch: \(error)")
                }
            )
            Self.logger.info("Sent page delta to Watch: \(delta)")
        } catch {
            Self.logger.error("Encoding error: \(error)")
        }
    }

    @MainActor
    func syncBooksToWatch() async {
        guard WCSession.default.activationState == .activated,
              let modelContext = modelContext else {
            Self.logger.warning("Cannot sync - WC not activated or context not configured")
            return
        }

        do {
            // Fetch all currently reading books
            let booksDescriptor = FetchDescriptor<Book>(
                sortBy: [SortDescriptor(\.title)]
            )
            let allBooks = try modelContext.fetch(booksDescriptor)
            let currentlyReading = allBooks.filter { $0.readingStatus == .currentlyReading }

            Self.logger.info("Syncing \(currentlyReading.count) books to Watch...")

            // Convert books to transferable format
            let bookTransfers = currentlyReading.map { book in
                BookTransfer(
                    id: book.id,
                    title: book.title,
                    author: book.author,
                    isbn: book.isbn,
                    coverImageURL: book.coverImageURL?.absoluteString,
                    totalPages: book.totalPages,
                    currentPage: book.currentPage,
                    bookTypeRawValue: book.bookTypeRawValue,
                    readingStatusRawValue: book.readingStatusRawValue,
                    dateAdded: book.dateAdded,
                    notes: book.notes
                )
            }

            // Fetch sessions for currently reading books
            let bookIds = currentlyReading.map { $0.id }
            let sessionsDescriptor = FetchDescriptor<ReadingSession>(
                sortBy: [SortDescriptor(\.startDate, order: .reverse)]
            )
            let allSessions = try modelContext.fetch(sessionsDescriptor)
            let relevantSessions = allSessions.filter { session in
                guard let book = session.book else { return false }
                return bookIds.contains(book.id)
            }

            Self.logger.info("Syncing \(relevantSessions.count) sessions to Watch...")

            // Convert sessions to transferable format
            let sessionTransfers = relevantSessions.compactMap { session -> SessionTransfer? in
                guard let bookId = session.book?.id else { return nil }
                return SessionTransfer(
                    id: session.id,
                    bookId: bookId,
                    startDate: session.startDate,
                    endDate: session.endDate,
                    startPage: session.startPage,
                    endPage: session.endPage,
                    durationMinutes: session.durationMinutes,
                    xpEarned: session.xpEarned,
                    isAutoGenerated: session.isAutoGenerated
                )
            }

            let booksData = try JSONEncoder().encode(bookTransfers)
            let sessionsData = try JSONEncoder().encode(sessionTransfers)

            // Use updateApplicationContext for guaranteed delivery
            try WCSession.default.updateApplicationContext([
                "books": booksData,
                "sessions": sessionsData
            ])
            Self.logger.info("Sent \(bookTransfers.count) books and \(sessionTransfers.count) sessions to Watch")
        } catch {
            Self.logger.error("Failed to sync to Watch: \(error)")
        }
    }
}

extension WatchConnectivityManager: WCSessionDelegate {
    nonisolated func session(
        _ session: WCSession,
        activationDidCompleteWith activationState: WCSessionActivationState,
        error: Error?
    ) {
        if let error = error {
            Self.logger.error("WC activation error: \(error)")
        } else {
            Self.logger.info("WC activated: \(activationState.rawValue)")
            // Sync books to watch when activated
            Task { @MainActor in
                await WatchConnectivityManager.shared.syncBooksToWatch()
            }
        }
    }

    nonisolated func sessionDidBecomeInactive(_ session: WCSession) {
        Self.logger.warning("WC session became inactive")
    }

    nonisolated func sessionDidDeactivate(_ session: WCSession) {
        Self.logger.warning("WC session deactivated")
        // Reactivate session for new watch
        session.activate()
    }

    nonisolated func sessionReachabilityDidChange(_ session: WCSession) {
        NotificationCenter.default.post(name: .watchReachabilityDidChange, object: nil)
    }

    nonisolated func session(
        _ session: WCSession,
        didReceiveMessage message: [String: Any]
    ) {
        Self.logger.info("iPhone received message")

        // Handle page delta
        if let pageDeltaData = message["pageDelta"] as? Data {
            Task { @MainActor in
                do {
                    let delta = try JSONDecoder().decode(PageDelta.self, from: pageDeltaData)
                    Self.logger.info("Received page delta: \(delta.delta) for book")
                    await self.handlePageDelta(delta)
                } catch {
                    Self.logger.error("Page delta decoding error: \(error)")
                }
            }
        }

        // Handle session from Watch
        if let sessionData = message["session"] as? Data {
            Task { @MainActor in
                do {
                    let sessionTransfer = try JSONDecoder().decode(SessionTransfer.self, from: sessionData)
                    Self.logger.info("Received session from Watch: \(sessionTransfer.endPage - sessionTransfer.startPage) pages")
                    await self.handleWatchSession(sessionTransfer)
                } catch {
                    Self.logger.error("Session decoding error: \(error)")
                }
            }
        }
    }

    @MainActor
    private func handlePageDelta(_ delta: PageDelta) async {
        guard let modelContext = modelContext else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Fetch the book by UUID
            let descriptor = FetchDescriptor<Book>(
                predicate: #Predicate<Book> { book in
                    book.id == delta.bookUUID
                }
            )
            let books = try modelContext.fetch(descriptor)

            guard let book = books.first else {
                Self.logger.warning("Book not found with UUID: \(delta.bookUUID)")
                return
            }

            // Update current page
            book.currentPage = min((book.totalPages ?? ReadingConstants.defaultMaxPages), book.currentPage + delta.delta)

            // Save context
            try modelContext.save()

            Self.logger.info("Updated book: \(book.title) to page \(book.currentPage)")

            // Update Live Activity if running
            await ReadingSessionActivityManager.shared.updateCurrentPage(book.currentPage)
        } catch {
            Self.logger.error("Failed to update book: \(error)")
        }
    }

    @MainActor
    private func handleWatchSession(_ transfer: SessionTransfer) async {
        guard let modelContext = modelContext else {
            Self.logger.warning("ModelContext not configured")
            return
        }

        do {
            // Check if session already exists
            let descriptor = FetchDescriptor<ReadingSession>(
                predicate: #Predicate<ReadingSession> { session in
                    session.id == transfer.id
                }
            )
            let existingSessions = try modelContext.fetch(descriptor)

            if let existingSession = existingSessions.first {
                // Update existing session
                existingSession.startDate = transfer.startDate
                existingSession.endDate = transfer.endDate
                existingSession.startPage = transfer.startPage
                existingSession.endPage = transfer.endPage
                existingSession.durationMinutes = transfer.durationMinutes
                existingSession.xpEarned = transfer.xpEarned
                existingSession.isAutoGenerated = transfer.isAutoGenerated
                Self.logger.info("Updated existing session from Watch")
            } else {
                // Find the book
                let bookDescriptor = FetchDescriptor<Book>(
                    predicate: #Predicate<Book> { book in
                        book.id == transfer.bookId
                    }
                )
                let books = try modelContext.fetch(bookDescriptor)

                guard let book = books.first else {
                    Self.logger.warning("Book not found for Watch session: \(transfer.bookId)")
                    return
                }

                // Create new session
                let session = ReadingSession(
                    id: transfer.id,
                    startDate: transfer.startDate,
                    endDate: transfer.endDate,
                    startPage: transfer.startPage,
                    endPage: transfer.endPage,
                    durationMinutes: transfer.durationMinutes,
                    xpEarned: transfer.xpEarned,
                    isAutoGenerated: transfer.isAutoGenerated,
                    book: book
                )
                modelContext.insert(session)
                Self.logger.info("Created new session from Watch: \(transfer.endPage - transfer.startPage) pages, \(transfer.xpEarned) XP")
            }

            try modelContext.save()
        } catch {
            Self.logger.error("Failed to handle Watch session: \(error)")
        }
    }
}
