//
//  ConnectivityTransfers.swift
//  Shlf
//
//  Created by Codex on 03/02/2026.
//

import Foundation

struct PageDelta: Codable, Sendable {
    let bookUUID: UUID
    let delta: Int
}

struct BookTransfer: Codable, Sendable {
    let id: UUID
    let title: String
    let author: String
    let isbn: String?
    let coverImageURL: String?
    let totalPages: Int?
    let currentPage: Int
    let bookTypeRawValue: String
    let readingStatusRawValue: String
    let dateAdded: Date
    let notes: String
}

struct SessionTransfer: Codable, Sendable {
    let id: UUID
    let bookId: UUID
    let startDate: Date
    let endDate: Date?
    let startPage: Int
    let endPage: Int
    let durationMinutes: Int
    let xpEarned: Int
    let isAutoGenerated: Bool
}

struct ProfileSettingsTransfer: Codable, Sendable {
    let hideAutoSessionsIPhone: Bool
    let hideAutoSessionsWatch: Bool
    let showSettingsOnWatch: Bool

    init(
        hideAutoSessionsIPhone: Bool,
        hideAutoSessionsWatch: Bool,
        showSettingsOnWatch: Bool = true
    ) {
        self.hideAutoSessionsIPhone = hideAutoSessionsIPhone
        self.hideAutoSessionsWatch = hideAutoSessionsWatch
        self.showSettingsOnWatch = showSettingsOnWatch
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let hideIPhone = try container.decode(Bool.self, forKey: .hideAutoSessionsIPhone)
        let hideWatch = try container.decode(Bool.self, forKey: .hideAutoSessionsWatch)
        let showSettings = try container.decodeIfPresent(Bool.self, forKey: .showSettingsOnWatch) ?? true
        self.init(
            hideAutoSessionsIPhone: hideIPhone,
            hideAutoSessionsWatch: hideWatch,
            showSettingsOnWatch: showSettings
        )
    }
}

struct ProfileStatsTransfer: Codable, Sendable {
    let totalXP: Int
    let currentStreak: Int
    let longestStreak: Int
    let lastReadingDate: Date?
}

struct LiveActivityStartTransfer: Codable, Sendable {
    let bookTitle: String
    let bookAuthor: String
    let totalPages: Int
    let startPage: Int
    let currentPage: Int
    let startTime: Date
}

struct LiveActivityUpdateTransfer: Codable, Sendable {
    let currentPage: Int
    let xpEarned: Int
}

struct LiveActivityStateTransfer: Codable, Sendable {
    let isPaused: Bool
}

