//
//  BookDetailWatchView.swift
//  ShlfWatch Watch App
//
//  Created by João Fernandes on 27/11/2025.
//

import SwiftUI
import SwiftData

struct BookDetailWatchView: View {
    @Environment(\.modelContext) private var modelContext
    @Bindable var book: Book
    @Query private var profiles: [UserProfile]

    @State private var showingAddPages = false

    private var profile: UserProfile? {
        profiles.first
    }

    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                // Book info
                VStack(spacing: 4) {
                    Text(book.title)
                        .font(.headline)
                        .multilineTextAlignment(.center)

                    Text(book.author)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                // Progress
                if let totalPages = book.totalPages {
                    VStack(spacing: 8) {
                        Text("\(book.currentPage)")
                            .font(.system(size: 48, weight: .bold, design: .rounded))
                            .foregroundStyle(.cyan)

                        Text("of \(totalPages) pages")
                            .font(.caption)
                            .foregroundStyle(.secondary)

                        ProgressView(value: Double(book.currentPage), total: Double(totalPages))
                            .tint(.cyan)
                    }
                    .padding(.vertical)
                }

                // Quick actions
                VStack(spacing: 8) {
                    Button {
                        addPages(1)
                    } label: {
                        Label("+1 Page", systemImage: "plus.circle.fill")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.borderedProminent)
                    .tint(.cyan)

                    Button {
                        addPages(5)
                    } label: {
                        Label("+5 Pages", systemImage: "plus.circle.fill")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.bordered)
                    .tint(.cyan)

                    Button {
                        showingAddPages = true
                    } label: {
                        Label("Custom", systemImage: "number")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.bordered)
                }
            }
            .padding()
        }
        .navigationTitle("Progress")
        .navigationBarTitleDisplayMode(.inline)
        .sheet(isPresented: $showingAddPages) {
            AddPagesWatchView(book: book)
        }
    }

    private func addPages(_ pages: Int) {
        let oldPage = book.currentPage
        book.currentPage = min((book.totalPages ?? 1000), book.currentPage + pages)

        // Send delta to iPhone via WatchConnectivity
        let delta = PageDelta(bookUUID: book.id, delta: pages)
        WatchConnectivityManager.shared.sendPageDelta(delta)

        // Create auto-generated session
        let pagesRead = book.currentPage - oldPage
        if pagesRead > 0, let profile = profile {
            let session = ReadingSession(
                startPage: oldPage,
                endPage: book.currentPage,
                durationMinutes: pagesRead * 2, // Estimate 2 min/page
                xpEarned: pagesRead * 3,
                isAutoGenerated: true,
                book: book
            )
            modelContext.insert(session)

            // Update goals
            let tracker = GoalTracker(modelContext: modelContext)
            tracker.updateGoals(for: profile)
        }
    }
}

struct AddPagesWatchView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @Bindable var book: Book
    @Query private var profiles: [UserProfile]

    @State private var pagesToAdd = 10

    private var profile: UserProfile? {
        profiles.first
    }

    var body: some View {
        VStack(spacing: 12) {
            Text("Add Pages")
                .font(.headline)

            Picker("Pages", selection: $pagesToAdd) {
                Text("5").tag(5)
                Text("10").tag(10)
                Text("15").tag(15)
                Text("20").tag(20)
                Text("30").tag(30)
            }
            .pickerStyle(.wheel)

            Button {
                addPages()
            } label: {
                Text("Add \(pagesToAdd)")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .tint(.cyan)

            Button("Cancel") {
                dismiss()
            }
            .buttonStyle(.bordered)
        }
        .padding()
    }

    private func addPages() {
        let oldPage = book.currentPage
        book.currentPage = min((book.totalPages ?? 1000), book.currentPage + pagesToAdd)

        // Send delta to iPhone via WatchConnectivity
        let delta = PageDelta(bookUUID: book.id, delta: pagesToAdd)
        WatchConnectivityManager.shared.sendPageDelta(delta)

        // Create auto-generated session
        let pagesRead = book.currentPage - oldPage
        if pagesRead > 0, let profile = profile {
            let session = ReadingSession(
                startPage: oldPage,
                endPage: book.currentPage,
                durationMinutes: pagesRead * 2,
                xpEarned: pagesRead * 3,
                isAutoGenerated: true,
                book: book
            )
            modelContext.insert(session)

            // Update goals
            let tracker = GoalTracker(modelContext: modelContext)
            tracker.updateGoals(for: profile)
        }

        dismiss()
    }
}
