//
//  SessionDetailWatchView.swift
//  ShlfWatch Watch App
//
//  Created by João Fernandes on 28/11/2025.
//

import SwiftUI
import SwiftData

struct SessionDetailWatchView: View {
    @Environment(\.themeColor) private var themeColor
    let session: ReadingSession

    private var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: session.startDate)
    }

    private var pagesRead: Int {
        session.endPage - session.startPage
    }

    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                // Main Stats
                VStack(spacing: 12) {
                    // Pages Read
                    StatCard(
                        icon: "book.fill",
                        value: "\(pagesRead)",
                        label: "Pages Read",
                        color: themeColor.color
                    )

                    // Duration
                    StatCard(
                        icon: "clock.fill",
                        value: "\(session.durationMinutes)",
                        label: "Minutes",
                        color: .orange
                    )

                    // XP Earned
                    StatCard(
                        icon: "star.fill",
                        value: "\(session.xpEarned)",
                        label: "XP Earned",
                        color: .yellow
                    )
                }

                // Page Range
                VStack(alignment: .leading, spacing: 8) {
                    Text("Progress")
                        .font(.caption2)
                        .foregroundStyle(.secondary)

                    HStack {
                        VStack {
                            Text(session.startPage, format: .number)
                                .font(.title3)
                                .fontWeight(.semibold)
                            Text("Start")
                                .font(.caption2)
                                .foregroundStyle(.secondary)
                        }
                        .frame(maxWidth: .infinity)

                        Image(systemName: "arrow.right")
                            .foregroundStyle(themeColor.color)

                        VStack {
                            Text(session.endPage, format: .number)
                                .font(.title3)
                                .fontWeight(.semibold)
                            Text("End")
                                .font(.caption2)
                                .foregroundStyle(.secondary)
                        }
                        .frame(maxWidth: .infinity)
                    }
                    .padding(.vertical, 8)
                    .background(.regularMaterial)
                    .cornerRadius(8)
                }

                // Date
                VStack(alignment: .leading, spacing: 4) {
                    Text("Date")
                        .font(.caption2)
                        .foregroundStyle(.secondary)

                    Text(formattedDate)
                        .font(.caption)
                }
                .frame(maxWidth: .infinity, alignment: .leading)

                // Session Type
                if session.isImported || !session.countsTowardStats {
                    Label("Imported Session", systemImage: "archivebox")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                } else if session.isAutoGenerated {
                    Label("Quick Log", systemImage: "bolt.fill")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                } else {
                    Label("Manual Session", systemImage: "hand.draw.fill")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                }
            }
            .padding()
        }
        .navigationTitle("Session Details")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct StatCard: View {
    let icon: String
    let value: String
    let label: String
    let color: Color

    var body: some View {
        HStack {
            Image(systemName: icon)
                .foregroundStyle(color)
                .font(.title2)
                .frame(width: 32)

            VStack(alignment: .leading, spacing: 2) {
                Text(value)
                    .font(.title3)
                    .fontWeight(.semibold)

                Text(label)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Spacer()
        }
        .padding()
        .background(.regularMaterial)
        .cornerRadius(10)
    }
}

#Preview {
    NavigationStack {
        SessionDetailWatchView(session: ReadingSession(
            startPage: 50,
            endPage: 75,
            durationMinutes: 45,
            xpEarned: 75,
            isAutoGenerated: false,
            book: nil
        ))
    }
}
